web:
    image: skyadmin/springweb
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - .:/data
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run

db:
  image: mysql:5.7
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: demo
    MYSQL_ROOT_PASSWORD: demo